name: Spellcheck

on:
  pull_request:
    branches:
      - main
      - next
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  check:
    uses: kitsuyui/gh-actions-workflows/.github/workflows/spellcheck.yml@main
